name: dso_env_rounding
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.16
  - numpy=1.19.0
  - pandas=1.3.5
  - matplotlib=3.5.3
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - sympy=1.10.1
  - seaborn=0.12.2
  - joblib=1.3.2
  - pillow=9.5.0
  - threadpoolctl=3.1.0
  - typing_extensions=4.7.1
  - pytz=2025.2
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - pip
  - pip:
      - absl-py==2.1.0
      - astor==0.8.1
      - click==8.1.8
      - commentjson==0.9.0
      - cycler==0.11.0
      - Cython==3.0.12
      - deap==1.4.3
      - dill==0.3.7
      - exceptiongroup==1.3.0
      - fonttools==4.38.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - h5py==3.8.0
      - importlib-metadata==6.7.0
      - iniconfig==2.0.0
      - Keras-Applications==1.0.8
      - Keras-Preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lark-parser==0.7.8
      - llvmlite==0.36.0
      - Markdown==3.4.4
      - MarkupSafe==2.1.5
      - mpmath==1.3.0
      - multiprocess==0.70.15
      - numba==0.53.1
      - packaging==24.0
      - pathos==0.3.1
      - pluggy==1.2.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - prettytable==3.7.0
      - progress==1.6.1
      - protobuf==3.20.3
      - pyparsing==3.1.4
      - pytest==7.4.4
      - PyYAML==6.0.1
      - tensorboard==1.14.0
      - tensorflow==1.14.0
      - tensorflow-estimator==1.14.0
      - termcolor==2.3.0
      - tomli==2.0.1
      - tqdm==4.67.1
      - wcwidth==0.2.13
      - Werkzeug==2.2.3
      - wrapt==1.16.0
      - zipp==3.15.0
      - -e git+https://github.com/dso-org/deep-symbolic-optimization.git@9a8400a4473ac3eb8f4262722abc32d9760eb7c8#egg=dso&subdirectory=dso 