name: dso_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.16
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - sympy
  - seaborn
  - joblib
  - pillow
  - threadpoolctl
  - typing_extensions
  - pytz
  - python-dateutil
  - six
  - pip
  - pip:
      - protobuf==3.20.3
      - tensorflow==1.14.0
      - numba==0.53.1
      - click
      - deap
      - pathos
      - progress
      - tqdm
      - commentjson
      - PyYAML
      - prettytable
      - pytest
      - cython
      - -e /home/mk422/Documents/DAC_SR/SR_algorithms/DeepSR/deep-symbolic-optimization/dso 