name: e2e_transformer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.12
  - numpy=1.21.5
  - pandas=1.3.5
  - matplotlib=3.5.1
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - sympy=1.10.1
  - seaborn=0.11.2
  - joblib=1.1.0
  - pillow=9.1.0
  - threadpoolctl=3.1.0
  - typing_extensions=4.1.1
  - pytz=2022.1
  - python-dateutil=2.8.2
  - six=1.16.0
  - pip
  - pip:
      - args==0.1.0
      - attrs==21.4.0
      - certifi==2021.10.8
      - charset-normalizer==2.0.12
      - clint==0.5.1
      - coverage==6.3.2
      - cycler==0.11.0
      - fonttools==4.31.2
      - functorch==0.1.0
      - idna==3.3
      - importlib-metadata==4.11.3
      - iniconfig==1.1.1
      - kiwisolver==1.4.2
      - mamba==0.11.2
      - mpmath==1.2.1
      - numexpr==2.8.1
      - packaging==21.3
      - pluggy==1.0.0
      - py==1.11.0
      - pyparsing==3.0.7
      - pytest==7.1.1
      - PyYAML==6.0
      - requests==2.27.1
      - tomli==2.0.1
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - tqdm==4.64.0
      - urllib3==1.26.9
      - zipp==3.8.0
      - sympytorch @ git+https://github.com/pakamienny/sympytorch@cb4cd0f516c2f1495ebbddd78fa93279e5f24c56 