name: evaluation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy=2.2.6
  - pandas=2.3.1
  - matplotlib=3.10.3
  - scipy=1.15.3
  - scikit-learn=1.7.1
  - sympy=1.14.0
  - seaborn=0.13.2
  - joblib=1.5.1
  - pillow=11.3.0
  - threadpoolctl=3.6.0
  - typing_extensions=4.14.1
  - pytz=2025.2
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - pip
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.59.0
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - logistro==1.1.0
      - plotly==6.2.0
      - mpmath==1.3.0
      - narwhals==1.48.0
      - orjson==3.11.0
      - packaging==25.0
      - pyparsing==3.2.3
      - simplejson==3.20.1
      - tzdata==2025.2 