name: generation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - mpmath
  - joblib
  - pillow
  - pyparsing
  - python-dateutil
  - pytz
  - seaborn
  - six
  - sympy
  - threadpoolctl
  - typing_extensions
  - tzdata
  - plotly
  - pip
  - pip:
      - DACBench==0.3.0
      - gymnasium==0.29.1
      - ioh>=0.3.0
      - fsspec==2025.7.0
      - Farama-Notifications==0.0.4
      - stable_baselines3==2.6.0
      - torch>=2.3,<3.0
      - torchvision
      - torchaudio 