name: generation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - mpmath=1.3.0
  - joblib=1.5.1
  - pillow=11.3.0
  - pyparsing=3.2.3
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - seaborn=0.13.2
  - six=1.17.0
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - typing_extensions=4.14.1
  - tzdata=2025.2
  - plotly>=5.0.0
  - pip
  - pip:
      - DACBench==0.3.0
      - gymnasium==0.29.1
      - ioh>=0.3.0
      - fsspec==2025.7.0
      - Farama-Notifications==0.0.4
      - stable_baselines3==2.6.0
      - jupyter
      - jupyterlab
      - jupyterlab_widgets
      - jupyterlab_server
      - jupyterlab_pygments
      - jupyter_server
      - jupyter_server_terminals
      - jupyter-console
      - jupyter-events
      - jupyter-lsp
      - jupyter_client
      - comm
      - ipykernel
      - ipython
      - ipywidgets
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - notebook
      - notebook_shim
      - prometheus_client
      - prompt_toolkit
      - qtconsole
      - QtPy
      - widgetsnbextension
      - traitlets
      - tornado
      - pyzmq
      - pure_eval
      - stack-data
      - debugpy
      - async-lru
      - anyio
      - argon2-cffi
      - argon2-cffi-bindings
      - isoduration
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - referencing
      - rfc3339-validator
      - rfc3986-validator
      - rfc3987-syntax
      - rpds-py
      - send2trash
      - terminado
      - tinycss2
      - webcolors
      - webencodings
      - websocket-client
      - tornado
      - platformdirs
      - filelock
      - packaging
      - typing-extensions
      - types-python-dateutil
      - overrides
      - markdown
      - markupsafe
      - matplotlib-inline
      - mistune
      - more-itertools
      - networkx
      - lark
      - fqdn
      - configspace
      - cloudpickle
      - comm
      - fastjsonschema
      - fonttools
      - imageio
      - jinja2
      - parso
      - pexpect
      - psutil
      - ptyprocess
      - pycparser
      - pygments
      - pyarrow
      - Pyro4
      - python-json-logger
      - qtpy
      - referencing
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - rfc3987-syntax
      - rpds-py
      - send2trash
      - terminado
      - tinycss2
      - webcolors
      - webencodings
      - websocket-client
      - werkzeug
      - widgetsnbextension
      - xz
      - zlib 