name: kan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy=1.24.4
  - pandas=2.0.1
  - matplotlib=3.6.2
  - scipy=1.15.3
  - scikit-learn=1.1.3
  - sympy=1.11.1
  - seaborn=0.13.2
  - joblib=1.5.1
  - pillow=11.3.0
  - threadpoolctl=3.6.0
  - typing_extensions=4.14.1
  - pytz=2025.2
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - pip
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - Jinja2==3.1.6
      - MarkupSafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pyparsing==3.2.3
      - PyYAML==6.0.2
      - torch==2.2.2
      - tqdm==4.66.2
      - triton==2.2.0
      - zipp==3.20.2
      - tzdata==2025.2 