name: kan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - sympy
  - seaborn
  - joblib
  - pillow
  - threadpoolctl
  - typing_extensions
  - pytz
  - python-dateutil
  - six
  - pip
  - pip:
      - torch==2.2.2
      - -e /home/mk422/Documents/DAC_SR/SR_algorithms/pykan 