name: linear
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.23
  - numpy=1.21.5
  - pandas=1.3.5
  - matplotlib=3.5.1
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - sympy=1.10.1
  - seaborn=0.11.2
  - joblib=1.1.0
  - pillow=9.1.0
  - threadpoolctl=3.1.0
  - typing_extensions=4.4.0
  - pytz=2022.1
  - python-dateutil=2.8.2
  - six=1.16.0
  - pip
  - pip:
      - args==0.1.0
      - attrs==21.4.0
      - backcall==0.2.0
      - cachetools==5.3.0
      - certifi==2021.10.8
      - charset-normalizer==2.0.12
      - clint==0.5.1
      - cloudpickle==2.2.1
      - contourpy==1.3.0
      - coverage==6.3.2
      - cycler==0.11.0
      - decorator==5.1.1
      - deepspeed==0.8.0
      - Farama-Notifications==0.0.4
      - fonttools==4.31.2
      - fsspec==2025.7.0
      - functorch==0.1.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - hjson==3.1.0
      - idna==3.3
      - importlib-metadata==4.11.3
      - importlib_resources==6.5.2
      - iniconfig==1.1.1
      - ioh==0.3.18
      - ipython==7.34.0
      - jedi==0.18.2
      - kiwisolver==1.4.2
      - mamba==0.11.2
      - matplotlib-inline==0.1.6
      - mpmath==1.2.1
      - networkx==2.6.3
      - ninja==1.11.1
      - numexpr==2.8.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==11.515.75
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - nvitop==0.11.0
      - packaging==23.0
      - parso==0.8.3
      - pickleshare==0.7.5
      - pluggy==1.0.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.1
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==11.0.0
      - pydantic==1.10.4
      - pyext==0.7
      - Pygments==2.14.0
      - pyparsing==3.0.7
      - pytest==7.1.1
      - requests==2.27.1
      - stable_baselines3==2.6.0
      - sympytorch==0.1.1
      - tensorboardX==2.5.1
      - termcolor==2.2.0
      - tomli==2.0.1
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - tqdm==4.64.0
      - traitlets==5.8.1
      - triton==3.3.1
      - urllib3==1.26.9
      - wcwidth==0.2.6
      - xgboost==1.6.2
      - zipp==3.8.0
      - zss==1.2.0 