name: psa_cmaes
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.4
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - sympy=1.13.1
  - seaborn=0.13.2
  - joblib=1.5.1
  - pillow=11.1.0
  - threadpoolctl=3.6.0
  - typing_extensions=4.12.2
  - pytz=2025.1
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - pip
  - pip:
      - ConfigSpace==1.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - Farama-Notifications==0.0.4
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - gymnasium==1.0.0
      - ioh==0.3.18
      - IOHexperimenter==0.2.9.2
      - Jinja2==3.1.5
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - Pygments==2.19.1
      - pyparsing==3.2.1
      - rich==13.9.4
      - stable_baselines3==2.4.0
      - torch==2.6.0
      - tqdm==4.66.5
      - triton==3.2.0
      - zipp==3.20.2
      - tzdata==2025.1
      - -e /cs/home/mk422/Documents/DAC_SR/thesis/ModularCMAES 