name: pysr_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy>=2.2.0
  - pandas>=2.3.0
  - scikit-learn>=1.7.0
  - scipy>=1.15.0
  - sympy>=1.14.0
  - joblib>=1.5.0
  - threadpoolctl>=3.6.0
  - typing_extensions>=4.14.0
  - pytz
  - python-dateutil
  - six
  - pip
  - pip:
      - click==8.2.1
      - filelock==3.18.0
      - juliacall==0.9.26
      - juliapkg==0.1.17
      - mpmath==1.3.0
      - pysr==1.5.9
      - semver==3.0.4
      - zipp==3.20.2
      - tzdata==2025.2 