name: q_lat
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.23
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - sympy
  - joblib
  - threadpoolctl
  - typing_extensions
  - pytz
  - python-dateutil
  - six
  - pip
  - pip:
      - feyn==3.4.0 