name: q_lat
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.20
  - numpy=1.24.4
  - pandas=2.0.3
  - matplotlib=3.7.5
  - scipy=1.10.1
  - scikit-learn=1.3.2
  - sympy=1.13.3
  - joblib=1.4.2
  - threadpoolctl=3.5.0
  - typing_extensions=4.14.1
  - pytz=2025.2
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - pip
  - pip:
      - cffi==1.17.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - feyn==3.4.0
      - fonttools==4.57.0
      - importlib_resources==6.4.5
      - kiwisolver==1.4.7
      - lark==1.2.2
      - pillow==10.4.0
      - pycparser==2.22
      - PyNaCl==1.5.0
      - pyparsing==3.1.4
      - svgwrite==1.4.3
      - zipp==3.20.2
      - tzdata==2025.2 