name: tpsr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.16
  - numpy=1.21.5
  - pandas=1.3.5
  - matplotlib=3.5.1
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - sympy=1.10.1
  - seaborn=0.11.2
  - joblib=1.1.0
  - pillow=9.1.0
  - threadpoolctl=3.1.0
  - typing_extensions=4.7.1
  - pytz=2022.1
  - python-dateutil=2.8.2
  - six=1.16.0
  - pip
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - anyio==3.7.1
      - args==0.1.0
      - arrow==1.2.3
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==21.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - blessed==1.21.0
      - boto3==1.33.13
      - botocore==1.33.13
      - cachetools==5.3.0
      - certifi==2021.10.8
      - charset-normalizer==2.0.12
      - clint==0.5.1
      - cloudpickle==2.2.1
      - coverage==6.3.2
      - croniter==1.3.15
      - cycler==0.11.0
      - dataclass-dict-convert==1.7.4
      - dateutils==0.6.12
      - decorator==5.1.1
      - deepdiff==6.7.1
      - deepspeed==0.8.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.3.0
      - fastapi==0.88.0
      - fonttools==4.31.2
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - functorch==0.1.0
      - gitdb==4.0.12
      - GitPython==3.1.44
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==3.8.0
      - hjson==3.1.0
      - hydra-core==1.0.0
      - idna==3.3
      - importlib-resources==5.12.0
      - iniconfig==1.1.1
      - inquirer==2.10.1
      - ipython==7.34.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - Jinja2==3.1.6
      - jmespath==1.0.1
      - jsons==1.6.3
      - kiwisolver==1.4.2
      - lightning==1.9.0
      - lightning-cloud==0.5.70
      - lightning-utilities==0.10.1
      - mamba==0.11.2
      - markdown-it-py==2.2.0
      - MarkupSafe==2.1.5
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mpmath==1.2.1
      - multidict==6.0.5
      - networkx==2.6.3
      - ninja==1.11.1
      - numexpr==2.8.1
      - nvidia-ml-py==11.515.75
      - nvitop==0.11.0
      - omegaconf==2.1.2
      - ordered-set==4.1.0
      - packaging==22.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==4.0.0
      - pluggy==1.0.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.1
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==11.0.0
      - pydantic==1.10.4
      - pyext==0.7
      - Pygments==2.14.0
      - PyJWT==2.8.0
      - pyparsing==3.0.7
      - pytest==7.1.1
      - python-editor==1.0.4
      - python-multipart==0.0.8
      - pytorch-lightning==1.9.0
      - PyYAML==6.0.1
      - readchar==4.0.5
      - requests==2.27.1
      - rich==13.8.1
      - s3transfer==0.8.2
      - sentry-sdk==2.33.2
      - setproctitle==1.3.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - starlette==0.22.0
      - starsessions==1.3.0
      - stringcase==1.2.0
      - sympytorch==0.1.1
      - tensorboardX==2.5.1
      - termcolor==2.2.0
      - tomli==2.0.1
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchmetrics==0.11.4
      - torchvision==0.12.0
      - tqdm==4.64.0
      - traitlets==5.8.1
      - typish==1.9.3
      - urllib3==1.26.20
      - uvicorn==0.22.0
      - wandb==0.18.7
      - wcwidth==0.2.6
      - websocket-client==1.6.1
      - websockets==11.0.3
      - xgboost==1.6.2
      - yarl==1.9.4
      - zss==1.2.0
      - -e git+https://github.com/deep-symbolic-mathematics/TPSR.git@bdff709f1bfabb9e1a98c25c63d4847f39c83020#egg=nesymres&subdirectory=nesymres/src 